# -*- coding: utf-8 -*-
#----------------------------------------------------------------------------#
# SConscript
# Lars Yencken <lars.yencken@gmail.com>
# vim: ts=4 sw=4 sts=4 et tw=78:
# Tue Feb  6 13:28:19 2007
#
#----------------------------------------------------------------------------#

""" Build file for the imgSeekLib package.
"""

#----------------------------------------------------------------------------#

Import('env')

env.Append(CXXFLAGS='-pthread -fno-strict-aliasing ')

objects = [
    env.SharedObject('imageDatabase.cpp'),
    env.SharedObject('listLong.cpp'),
    env.SharedObject('signature.cpp'),
    env.SharedObject('haar.cpp'),
    env.SharedObject('imgdb_export.cpp'),
]

env.SharedLibrary('imgdb', objects)

#----------------------------------------------------------------------------#
