# -*- coding: utf-8 -*-
#----------------------------------------------------------------------------#
# SConstruct
# Lars Yencken <lars.yencken@gmail.com>
# vim: ts=4 sw=4 sts=4 et tw=78:
# Thu Aug 23 21:34:17 2007
#
#----------------------------------------------------------------------------#

""" 
"""

#----------------------------------------------------------------------------#

import os

#----------------------------------------------------------------------------#

glibmm_cflags = os.popen('pkg-config --cflags glibmm-2.4').read().strip()
glibmm_libs = os.popen('pkg-config --libs glibmm-2.4').read().strip().split()

env = Environment(
#        CPPPATH=sysconfig.get_python_inc(),
#        LIBPATH=sysconfig.get_config_var('LIBPL'),
#        SHLIBPREFIX='',
#        LIBS=['boost_python', 'python%s' % pythonVersion],
        CXXFLAGS=glibmm_cflags,
        LIBS=glibmm_libs,
    )

env.Program('unicodeCat', 'unicodeCat.cpp')

#----------------------------------------------------------------------------#

