# -*- coding: utf-8 -*-
#----------------------------------------------------------------------------#
# SConstruct
# Lars Yencken <lars.yencken@gmail.com>
# vim: ts=4 sw=4 sts=4 et tw=78:
# Sat Aug 25 14:09:43 2007
#
#----------------------------------------------------------------------------#

"""
"""

#----------------------------------------------------------------------------#

import os

#----------------------------------------------------------------------------#

glibIncludes = os.popen('pkg-config --cflags glibmm-2.4').read().strip()
glibLibs = os.popen('pkg-config --libs glibmm-2.4').read().strip().split()

env = Environment(
        CXXFLAGS=glibIncludes,
        LIBS=glibLibs,
    )

env.SharedLibrary('cjktools', 'scripts.cpp pystring.cpp'.split())
